name: bookify_audio
description: "Bookify Audio"

version: 1.0.1+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  youtube_explode_dart: ^2.3.6
  shared_preferences: ^2.5.2
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  audio_service: ^0.18.17
  just_audio: ^0.9.46
  cached_network_image: ^3.4.1
  flutter_lints: ^5.0.0
  http: ^1.3.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

icons_launcher:
  image_path: "assets/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/splash.png
    - CHANGELOG.md

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700